---
all:
  hosts:
    ansible_target:
      ansible_port: 20023
      ansible_host: localhost
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/casadilla/workingdir/bolt_comparison/.vagrant/machines/ansible_target/virtualbox/private_key
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
